# Generated by Django 3.2.4 on 2021-08-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='home.department'),
        ),
    ]
